### ISSUE TITLE
Rename oai-amf/interface-sba.yaml file

### ISSUE THREAD

**Issue by electrocucaracha** [OPENAIRINTERFACE/oai-packages#5]
This file is used to [define](https://github.com/OPENAIRINTERFACE/oai-packages/blob/r2/oai-amf/interface-sba.yaml#L4) the `sbi` interface, so the filename should reflect that.

**Comment by arora-sagar** [comment]
@electrocucaracha Okay, I will change the filename for all NFs

**Comment by arora-sagar** [comment]
Issue solved
